language: cpp 

os: osx
osx_image: xcode10

sudo: required

branches:
  only:
  - master
  - ci

before_install:
- brew install hugo doxygen
- npm install winston commander object-assign xml2js handlebars gulp vinyl-ftp gulp-util minimist
#- git clone https://github.com/sourcey/moxygen
#- git clone https://github.com/ariadne-cps/ariadne ariadne

script:
#- cd ariadne
#- mkdir build; cd build
#- cmake ..
# - make doc
#- cd ../..
#- mkdir api-docs
# - moxygen/bin/moxygen.js --anchors --groups --classes --output=api-docs/%s.md ariadne/docs/xml 
- hugo

after_success:
- gulp deploy --user $FTP_USER --password $FTP_PASSWORD
