baseURL = "http://www.ariadne-cps.org/"
languageCode = "en-us"
title = "Ariadne"
theme = "beautifulhugo"
copyright = "Luca Geretti" 
 
[author]
  name = "Luca Geretti"

[Params]
  bartitle = "Ariadne: C++/Python Library for Formal Verification of Cyber-Physical Systems"
  subtitle = "C++/Python library for formal verification of cyber-physical systems, using reachability analysis and rigorous numerics on nonlinear hybrid automata"
  logo = "img/ariadne.png"
  favicon = "img/ariadne.ico"
  rss = true
  mainSections = ["post","posts"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
    name = "About"
    url = "about"
    weight = 1

[[menu.main]]
    name = "Publications"
    url = "publications"
    weight = 2

[[menu.main]]
    name = "Installation"
    url = "installation"
    weight = 3

[[menu.main]]
    name = "Tutorial"
    url = "tutorial"
    weight = 4

#[[menu.main]]
#    name = "Docs"
#    url = "docs"
#    weight = 5
