baseURL = "http://www.ariadne-cps.org/"
languageCode = "en-us"
title = "Ariadne"
theme = "beautifulhugo"
copyright = "Luca Geretti" 
 
[author]
  name = "Luca Geretti"

[Params]
  bartitle = "Ariadne: A C++ Library for Formal Verification of Cyber-Physical Systems"
  subtitle = "A C++ library for formal verification of cyber-physical systems, using reachability analysis for nonlinear hybrid automata"
  logo = "img/ariadne.png"
  favicon = "img/ariadne.ico"
  rss = true

[[menu.main]]
    name = "Publications"
    url = "publications"
    weight = 2

[[menu.main]]
    name = "Installation"
    url = "installation"
    weight = 3

[[menu.main]]
    name = "About"
    url = "about"
    weight = 1
