name: Deploy

on:
  push:
    branches:
    - master
    - actions
  pull_request:

env:
  FTP_USER: ${{ secrets.FTP_USER }}
  FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        brew install hugo
        npm install -g gulp vinyl-ftp gulp-util minimist --save-dev
        npm install gulp vinyl-ftp gulp-util minimist
    
    - name: Build
      run: |
        git submodule update --init --recursive
        hugo

    - name: Upload
      run: gulp deploy --user $FTP_USER --password $FTP_PASSWORD
        
